import axios from "axios";
import qs from 'qs';
import { useUserStore } from '../stores/user';

const baseURL = '/v1/';

const api = axios.create({
    baseURL: baseURL,
    timeout: 1000 * 180,
    withCredentials: true // 允许携带Cookie
});

// 巻加缺失的图标导入
import { 
    User, Lock, Document, DataAnalysis, Search, Coin, Setting, Key,
    HomeFilled, ArrowRight, Plus, Refresh, Delete, Monitor, Promotion, CopyDocument
} from '@element-plus/icons-vue';

// 响应拦截器
api.interceptors.response.use(
    response => {
        return response;
    },
    error => {
        if (error.response && error.response.status === 401) {
            const userStore = useUserStore();
            userStore.logout();
            window.location.href = '/#/login';
        }
        return Promise.reject(error);
    }
);

// ==================== 认证相关 ====================
export function ApiLogin(data) {
    return api.post("auth/login", qs.stringify(data));
}

export function ApiRegister(data) {
    return api.post("auth/register", qs.stringify(data));
}

export function ApiLogout() {
    return api.post("auth/logout");
}

export function ApiGetUserInfo() {
    return api.get("user/info");
}

export function ApiChangePassword(data) {
    return api.post("user/changePassword", qs.stringify(data));
}

export function ApiSelectDatabase(data) {
    return api.post("user/selectDatabase", qs.stringify(data));
}

// ==================== 用户管理（管理员） ====================
export function ApiGetUsers(params) {
    return api.get("admin/users", { params });
}

export function ApiResetPassword(data) {
    return api.post("admin/users/resetPassword", qs.stringify(data));
}

export function ApiUpdateUserStatus(data) {
    return api.post("admin/users/status", qs.stringify(data));
}

export function ApiDeleteUser(id) {
    return api.delete(`admin/users/${id}`);
}

export function ApiUpdateUserRole(data) {
    return api.post("admin/users/role", qs.stringify(data));
}

// ==================== 数据库管理 ====================
export function ApiGetDatabases(params) {
    return api.get("databases", { params });
}

export function ApiGetDatabaseInfo(id) {
    return api.get(`databases/${id}`);
}

export function ApiCreateDatabase(data) {
    return api.post("databases/create", qs.stringify(data));
}

export function ApiAutoGenerateDatabase(data) {
    return api.post("databases/autoGenerate", qs.stringify(data));
}

export function ApiClaimDatabase(id) {
    return api.post(`databases/${id}/claim`);
}

export function ApiReleaseDatabase(id) {
    return api.post(`databases/${id}/release`);
}

export function ApiUpdateDatabase(id, data) {
    return api.put(`databases/${id}`, qs.stringify(data));
}

export function ApiDeleteDatabase(id) {
    return api.delete(`databases/${id}`);
}

// ==================== 同盟管理 ====================
export function ApiGetTeamUser() {
    return api.get("getTeamUser");
}

export function ApiGetTeamGroup() {
    return api.get("getTeamGroup");
}

// ==================== 任务管理 ====================
export function ApiCreateTask(data) {
    return api.post("createTask", qs.stringify(data, { arrayFormat: 'repeat' }));
}

export function ApiGetTaskList() {
    return api.get("getTaskList");
}

export function ApiGetGroupWu() {
    return api.get("getGroupWu");
}

export function ApiDelTask(id) {
    return api.get(`deleteTask/${id}`);
}

export function ApiGetTask(id, refresh = false) {
    return api.get(`getTask/${id}${refresh ? '?refresh=1' : ''}`);
}

// ==================== 战报管理 ====================
export function ApiSetTaskUserLeave(id, data) {
    return api.post(`task/${id}/leave`, qs.stringify(data));
}

export function ApiEnableGetReport(data) {
    return api.post("enable/getReport", qs.stringify(data, { arrayFormat: 'repeat' }));
}

export function ApiDisableGetReport() {
    return api.get("disable/getReport");
}

export function ApiGetReportNumByTaskId(id) {
    return api.get(`getReportNumByTaskId/${id}`);
}

export function ApiStatisticsReport(id) {
    return api.get(`statisticsReport/${id}`);
}

export function ApiDelTaskReport(id) {
    return api.get(`deleteTaskReport/${id}`);
}

export function ApiEnableGetBattleReport() {
    return api.get("enable/getBattleReport");
}

export function ApiDisableGetBattleReport() {
    return api.get("disable/getBattleReport");
}

// ==================== 排行榜抓包开关 ====================
export function ApiEnableGetLeaderboard() {
    return api.get("enable/getLeaderboard");
}

export function ApiDisableGetLeaderboard() {
    return api.get("disable/getLeaderboard");
}

// ==================== 成员历史 ====================
export function ApiGetMemberHistory(params) {
    return api.get("member/history", { params });
}

// ==================== 翻地记录 ====================
export function ApiGetLandRecords(params) {
    return api.get("land/records", { params });
}

export function getExportLandRecordsUrl(params, sessionId) {
    const query = new URLSearchParams();
    if (params.player_name) query.append('player_name', params.player_name);
    if (params.is_success) query.append('is_success', params.is_success);
    if (params.only_members) query.append('only_members', params.only_members);
    if (params.group_name) query.append('group_name', params.group_name);
    if (params.start_time) query.append('start_time', params.start_time);
    if (params.end_time) query.append('end_time', params.end_time);
    if (sessionId) query.append('session_id', sessionId);
    return `/v1/land/records/export?${query.toString()}`;
}

export function ApiGetLandRecordsStats(params) {
    return api.get("land/records/stats", { params });
}

// ==================== 排行榜看板 ====================
export function ApiGetUnionLeaderboard(params) {
    return api.get("stzb/leaderboard/union", { params });
}

export function ApiGetPersonalLeaderboard(params) {
    return api.get("stzb/leaderboard/personal", { params });
}

export function ApiGetTerritoryLeaderboard(params) {
    return api.get("stzb/leaderboard/territory", { params });
}

// ==================== 每日报告 ====================
export function ApiGetDailyReportList(params) {
    return api.get("daily-report/list", { params });
}

export function ApiGetDailyReport(date) {
    return api.get(`daily-report/${date}`);
}

export function ApiGetDailyReportText(date) {
    return api.get(`daily-report/${date}/text`);
}

export function ApiGenerateDailyReport() {
    return api.post("daily-report/generate");
}

export function ApiDeleteDailyReport(date) {
    return api.delete(`daily-report/${date}`);
}

// ==================== 安全配置管理（管理员） ====================
export function ApiGetHostCheckConfig() {
    return api.get("security/host-check");
}

export function ApiSaveHostCheckConfig(enabled) {
    const formData = new FormData();
    formData.append('enabled', enabled ? '1' : '0');
    return api.post("security/host-check/save", formData);
}

// ==================== 数据清理管理（管理员） ====================
export function ApiExecuteCleanup(type = 'auto') {
    return api.post("admin/cleanup/execute", qs.stringify({ type }));
}
