import axios from "axios";
import qs from 'qs';
import { useUserStore } from '../store/user';

const baseURL = '/v1/';

export const api = axios.create({
    baseURL: baseURL,
    timeout: 1000 * 180,
    withCredentials: true,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
    }
});

api.interceptors.request.use(config => {
    if (config.data && typeof config.data === 'string') {
        config.headers['Content-Type'] = 'application/x-www-form-urlencoded';
    }
    return config;
});

api.interceptors.response.use(
    response => {
        return response;
    },
    error => {
        if (error.response && error.response.status === 401) {
            const currentPath = window.location.hash.replace('#', '') || '/';
            if (currentPath !== '/login') {
                const userStore = useUserStore.getState();
                userStore.logout();
                window.location.href = '/#/login';
            }
        }
        return Promise.reject(error);
    }
);

// ==================== 认证相关 ====================
export function ApiLogin(data: any) {
    return api.post("auth/login", qs.stringify(data));
}

export function ApiRegister(data: any) {
    return api.post("auth/register", qs.stringify(data));
}

export function ApiLogout() {
    return api.post("auth/logout");
}

export function ApiGetUserInfo() {
    return api.get("user/info");
}

export function ApiChangePassword(data: any) {
    return api.post("user/changePassword", qs.stringify(data));
}

export function ApiSelectDatabase(data: any) {
    return api.post("user/selectDatabase", qs.stringify(data));
}

// ==================== 用户管理（管理员） ====================
export function ApiGetUsers(params: any) {
    return api.get("admin/users", { params });
}

export function ApiResetPassword(data: any) {
    return api.post("admin/users/resetPassword", qs.stringify(data));
}

export function ApiUpdateUserStatus(data: any) {
    return api.post("admin/users/status", qs.stringify(data));
}

export function ApiDeleteUser(id: any) {
    return api.delete(`admin/users/${id}`);
}

export function ApiUpdateUserRole(data: any) {
    return api.post("admin/users/role", qs.stringify(data));
}

// ==================== 数据库管理 ====================
export function ApiGetDatabases(params?: any) {
    return api.get("databases", { params });
}

export function ApiGetDatabaseInfo(id: any) {
    return api.get(`databases/${id}`);
}

export function ApiCreateDatabase(data: any) {
    return api.post("databases/create", qs.stringify(data));
}

export function ApiAutoGenerateDatabase(data: any) {
    return api.post("databases/autoGenerate", qs.stringify(data));
}

export function ApiClaimDatabase(id: any) {
    return api.post(`databases/${id}/claim`);
}

export function ApiReleaseDatabase(id: any) {
    return api.post(`databases/${id}/release`);
}

export function ApiUpdateDatabase(id: any, data: any) {
    return api.put(`databases/${id}`, qs.stringify(data));
}

export function ApiDeleteDatabase(id: any) {
    return api.delete(`databases/${id}`);
}

// ==================== 同盟管理 ====================
export function ApiGetTeamUser() {
    return api.get("getTeamUser");
}

export function ApiGetTeamGroup() {
    return api.get("getTeamGroup");
}

// ==================== 任务管理 ====================
export function ApiCreateTask(data: any) {
    return api.post("createTask", qs.stringify(data, { arrayFormat: 'repeat' }));
}

export function ApiGetTaskList() {
    return api.get("getTaskList");
}

export function ApiGetGroupWu() {
    return api.get("getGroupWu");
}

export function ApiDelTask(id: any) {
    return api.get(`deleteTask/${id}`);
}

export function ApiGetTask(id: any, refresh = false) {
    return api.get(`getTask/${id}${refresh ? '?refresh=1' : ''}`);
}

// ==================== 战报管理 ====================
export function ApiSetTaskUserLeave(id: any, data: any) {
    return api.post(`task/${id}/leave`, qs.stringify(data));
}

export function ApiEnableGetReport(data: any) {
    return api.post("enable/getReport", qs.stringify(data, { arrayFormat: 'repeat' }));
}

export function ApiDisableGetReport() {
    return api.get("disable/getReport");
}

export function ApiGetReportNumByTaskId(id: any) {
    return api.get(`getReportNumByTaskId/${id}`);
}

export function ApiStatisticsReport(id: any) {
    return api.get(`statisticsReport/${id}?refresh=1`);
}

export function ApiDelTaskReport(id: any) {
    return api.get(`deleteTaskReport/${id}`);
}

export function ApiEnableGetBattleReport() {
    return api.get("enable/getBattleReport");
}

export function ApiDisableGetBattleReport() {
    return api.get("disable/getBattleReport");
}

// ==================== 排行榜抓包开关 ====================
export function ApiEnableGetLeaderboard() {
    return api.get("enable/getLeaderboard");
}

export function ApiDisableGetLeaderboard() {
    return api.get("disable/getLeaderboard");
}

// ==================== 成员历史 ====================
export function ApiGetMemberHistory(params: any) {
    return api.get("member/history", { params });
}

// ==================== 翻地记录 ====================
export function ApiGetLandRecords(params: any) {
    return api.get("land/records", { params });
}

export function getExportLandRecordsUrl(params: any, sessionId: any) {
    const query = new URLSearchParams();
    if (params.player_name) query.append('player_name', params.player_name);
    if (params.is_success) query.append('is_success', params.is_success);
    if (params.only_members) query.append('only_members', params.only_members);
    if (params.group_name) query.append('group_name', params.group_name);
    if (params.start_time) query.append('start_time', params.start_time);
    if (params.end_time) query.append('end_time', params.end_time);
    if (sessionId) query.append('session_id', sessionId);
    return `/v1/land/records/export?${query.toString()}`;
}

export function ApiGetLandRecordsStats(params: any) {
    return api.get("land/records/stats", { params });
}

// ==================== 排行榜看板 ====================
export function ApiGetUnionLeaderboard(params: any) {
    return api.get("stzb/leaderboard/union", { params });
}

export function ApiGetPersonalLeaderboard(params: any) {
    return api.get("stzb/leaderboard/personal", { params });
}

export function ApiGetTerritoryLeaderboard(params: any) {
    return api.get("stzb/leaderboard/territory", { params });
}

// ==================== 数据包捕获 ====================
export function ApiStartPacketCapture() {
    return api.post("packet-capture/start");
}

export function ApiStopPacketCapture() {
    return api.post("packet-capture/stop");
}

export function ApiGetPacketCaptureStats() {
    return api.get("packet-capture/stats");
}

export function ApiGetPackets(params?: any) {
    return api.get("packet-capture/packets", { params });
}

// ==================== 聊天消息（724协议） ====================
export function ApiEnableGetChatMessage() {
    return api.post("enable/getChatMessage");
}

export function ApiDisableGetChatMessage() {
    return api.get("disable/getChatMessage");
}

export function ApiGetChatMessageList(params: any) {
    return api.get("chat/messages", { params });
}

export function ApiGetChatMessageStats() {
    return api.get("chat/stats");
}

export function ApiDeleteChatMessages(beforeTime?: string) {
    const params = beforeTime ? `?before_time=${beforeTime}` : '';
    return api.delete(`chat/messages${params}`);
}

// ==================== 檄文（3788协议） ====================
export function ApiEnableGetManifesto() {
    return api.post("enable/getManifesto");
}

export function ApiDisableGetManifesto() {
    return api.get("disable/getManifesto");
}

export function ApiGetManifestoList(params: any) {
    return api.get("manifesto/list", { params });
}

export function ApiGetManifestoStats() {
    return api.get("manifesto/stats");
}

export function ApiDeleteManifestos(beforeTime?: string) {
    const params = beforeTime ? `?before_time=${beforeTime}` : '';
    return api.delete(`manifesto/list${params}`);
}

// ==================== 每日报告 ====================
export function ApiGetDailyReportList(params: any) {
    return api.get("daily-report/list", { params });
}

export function ApiGetDailyReport(date: any) {
    return api.get(`daily-report/${date}`);
}

export function ApiGetDailyReportText(date: any) {
    return api.get(`daily-report/${date}/text`);
}

export function ApiGenerateDailyReport() {
    return api.post("daily-report/generate");
}

export function ApiDeleteDailyReport(date: any) {
    return api.delete(`daily-report/${date}`);
}

// ==================== 安全配置管理（管理员） ====================
export function ApiGetHostCheckConfig() {
    return api.get("security/host-check");
}

export function ApiSaveHostCheckConfig(enabled: boolean) {
    const formData = new FormData();
    formData.append('enabled', enabled ? '1' : '0');
    return api.post("security/host-check/save", formData);
}

export function ApiGetIpWhitelist() {
    return api.get("ip-whitelist");
}

export function ApiSaveIpWhitelist(enabled: boolean, whitelist: string) {
    const formData = new FormData();
    formData.append('enabled', enabled ? '1' : '0');
    formData.append('whitelist', whitelist);
    return api.post("ip-whitelist/save", formData);
}

// ==================== 数据清理管理（管理员） ====================
export function ApiExecuteCleanup(type = 'auto') {
    return api.post("admin/cleanup/execute", qs.stringify({ type }));
}

// ==================== 队伍查询 ====================
export function ApiGetPlayerTeam(params: any) {
    return api.get("stzb/player/team/get", { params });
}

export function ApiGetPlayerTeamByKey(params: any) {
    return api.get("stzb/player/team/getByKey", { params });
}

// ==================== 战场人数统计 ====================
export function ApiGetBattlefieldStats(params?: any) {
  return api.get("battle/battlefield-stats", { params });
}

export function ApiGetBattleReports(params?: any) {
  return api.get("battle/reports", { params });
}

export function ApiDeleteBattleReports(data: { wid?: string; ids?: string }) {
  const params = new URLSearchParams();
  if (data.wid) params.append('wid', data.wid);
  if (data.ids) params.append('ids', data.ids);
  return api.delete(`battle/reports?${params.toString()}`);
}

export function ApiMigrateWidFormat() {
  return api.post("battle/migrate-wid");
}

// ==================== 战场实时监控（5028协议） ====================
export function ApiGetBattlefieldRealtimeStats() {
  return api.get("battlefield-realtime/stats");
}

export function ApiEnableBattlefieldRealtime() {
  return api.get("enable/getBattlefieldRealtime");
}

export function ApiDisableBattlefieldRealtime() {
  return api.get("disable/getBattlefieldRealtime");
}

export function ApiGetBattlefieldRealtimePackets(params?: any) {
  return api.get("battlefield-realtime/packets", { params });
}

export function ApiClearBattlefieldRealtimePackets() {
  return api.delete("battlefield-realtime/packets");
}

export function ApiSearchRealtimeMonitorTeams(params: any) {
  return api.get("statistics/player-teams/realtime-search", { params });
}
