/**
 * API接口定义 - 根据API文档完整实现
 */
const { get, post, put, del, request } = require('../utils/request')

/**
 * ==================== 认证相关 ====================
 */

// 用户登录
function login(username, password) {
  return post('/auth/login', { username, password }, false)
}

// 用户注册
function register(username, password, nickname) {
  return post('/auth/register', { username, password, nickname }, false)
}

// 用户登出
function logout() {
  return post('/auth/logout', {}, false)
}

// 获取用户信息
function getUserInfo() {
  return get('/user/info')
}

// 修改密码
function changePassword(oldPassword, newPassword) {
  return post('/user/changePassword', {
    old_password: oldPassword,
    new_password: newPassword
  })
}

// 选择数据库
function selectDatabase(databaseId) {
  return post('/user/selectDatabase', {
    database_id: databaseId
  })
}

/**
 * ==================== 数据库管理 ====================
 */

// 获取数据库列表
function getDatabases(page = 1, pageSize = 20) {
  return get('/databases', { page, page_size: pageSize, client_type: 'miniprogram' })
}

// 获取数据库信息
function getDatabaseInfo(id) {
  return get(`/databases/${id}`)
}

// 创建数据库
function createDatabase(name, displayName) {
  return post('/databases/create', {
    name,
    display_name: displayName
  })
}

// 自动生成数据库
function autoGenerateDatabase() {
  return post('/databases/autoGenerate', {})
}

// 认领数据库
function claimDatabase(id) {
  return post(`/databases/${id}/claim`)
}

// 释放数据库
function releaseDatabase(id) {
  return post(`/databases/${id}/release`)
}

// 更新数据库
function updateDatabase(id, data) {
  return put(`/databases/${id}`, data)
}

// 删除数据库
function deleteDatabase(id) {
  return del(`/databases/${id}`)
}

/**
 * ==================== 同盟成员 ====================
 */

// 获取同盟成员列表
function getTeamUsers(group) {
  const params = group ? { group } : {}
  return get('/getTeamUser', params, true, true)
}

// 获取同盟分组列表
function getTeamGroups() {
  return get('/getTeamGroup', {}, true, true)
}

/**
 * ==================== 任务管理 ====================
 */

// 获取任务列表
function getTaskList() {
  return get('/getTaskList', {}, true, true)
}

// 获取任务详情
function getTaskDetail(tid) {
  return get(`/getTask/${tid}`, {}, true, true)
}

// 创建任务
function createTask(data) {
  return post('/createTask', data, true, true)
}

// 删除任务
function deleteTask(tid) {
  return get(`/deleteTask/${tid}`, {}, true, true)
}

function setTaskUserLeave(tid, userId, isLeave, reason = '') {
  return post(`/task/${tid}/leave`, {
    user_id: userId,
    is_leave: isLeave ? 1 : 0,
    reason
  }, true, true)
}

/**
 * ==================== 战报管理 ====================
 */

// 启用战报抓取
function enableGetReport(pos, startTime, endTime) {
  const params = { pos }
  if (startTime) params.start_time = startTime
  if (endTime) params.end_time = endTime
  return post('/enable/getReport', params, true, true)
}

// 停止战报抓取
function disableGetReport() {
  return get('/disable/getReport', {}, true, true)
}

// 获取任务战报数量
function getReportNum(tid) {
  return get(`/getReportNumByTaskId/${tid}`, {}, true, true)
}

// 获取任务战报列表
function getTaskReportList(tid, page = 1, pageSize = 20, attackName) {
  const params = { page, page_size: pageSize }
  if (attackName) params.attack_name = attackName
  return get(`/getTaskReportList/${tid}`, params, true, true)
}

// 统计战报考勤
function statisticsReport(tid) {
  return get(`/statisticsReport/${tid}`, {}, true, true)
}

// 删除任务战报
function deleteTaskReport(tid) {
  return get(`/deleteTaskReport/${tid}`, {}, true, true)
}

// 获取分组武勋统计
function getGroupWu() {
  return get('/getGroupWu', {}, true, true)
}

// 启用战斗数据抓取
function enableGetBattleReport() {
  return post('/enable/getBattleReport', {}, true, true)
}

// 停止战斗数据抓取
function disableGetBattleReport() {
  return get('/disable/getBattleReport', {}, true, true)
}

// 获取详细战报列表
function getReportList(params) {
  return get('/stzb/report/list', params, true, true)
}

// 获取战报详情
function getBattleReportDetail(battleId) {
  return get(`/battle/report/${battleId}`, {}, true, true)
}

// 获取战斗报告列表（分页）
function getBattleReportList(params) {
  return get('/battle/reports', params, true, true)
}

/**
 * ==================== 成员历史 ====================
 */

// 获取成员变动历史
function getMemberHistory(params) {
  return get('/member/history', params, true, true)
}

// 获取翻地记录
function getLandRecords(params) {
  return get('/land/records', params, true, true)
}

// 导出翻地记录
function exportLandRecords() {
  return get('/land/records/export', {}, true, true)
}

// 获取翻地统计
function getLandRecordsStats(playerName) {
  return get('/land/records/stats', { player_name: playerName }, true, true)
}

/**
 * ==================== 玩家队伍 ====================
 */

// 获取玩家队伍配置
function getPlayerTeam(atkname, atkunionname, idu) {
  return get('/stzb/player/team/get', {
    atkname: atkname || '',
    atkunionname: atkunionname || '',
    idu: idu || ''
  }, true, true)
}

// 按关键词获取队伍
function getPlayerTeamByKey(key) {
  return get('/stzb/player/team/getByKey', { key }, true, true)
}

/**
 * ==================== 排行榜看板 ====================
 */

// 获取同盟排行榜
function getUnionLeaderboard(params) {
  return get('/stzb/leaderboard/union', params, true, true)
}

// 获取个人积分排行
function getPersonalLeaderboard(params) {
  return get('/stzb/leaderboard/personal', params, true, true)
}

// 获取领地排行榜
function getTerritoryLeaderboard(params) {
  return get('/stzb/leaderboard/territory', params, true, true)
}

// 启用排行榜抓取
function enableGetLeaderboard() {
  return post('/enable/getLeaderboard', {}, true, true)
}

// 关闭排行榜抓取
function disableGetLeaderboard() {
  return get('/disable/getLeaderboard', {}, true, true)
}

/**
 * ==================== 每日报告 ====================
 */

// 获取每日报告列表
function getDailyReportList() {
  return get('/daily-report/list', {}, true, true)
}

// 获取每日报告详情
function getDailyReport(date) {
  return get(`/daily-report/${date}`, {}, true, true)
}

// 获取每日报告文本
function getDailyReportText(date) {
  return get(`/daily-report/${date}/text`, {}, true, true)
}

// 生成今日报告
function generateDailyReport() {
  return post('/daily-report/generate', {}, true, true)
}

// 删除每日报告
function deleteDailyReport(date) {
  return del(`/daily-report/${date}`, {}, true, true)
}

/**
 * ==================== 分享访问 ====================
 */

// 分享任务列表
function shareTaskList(dbId) {
  return get('/share/taskList', { db_id: dbId }, false)
}

// 分享任务详情
function shareTaskDetail(tid, dbId) {
  return get(`/share/task/${tid}`, { db_id: dbId }, false)
}

// 分享任务战报列表
function shareTaskReportList(tid, dbId) {
  return get(`/share/taskReportList/${tid}`, { db_id: dbId }, false)
}

// 分享战报数量
function shareReportNum(tid, dbId) {
  return get(`/share/reportNum/${tid}`, { db_id: dbId }, false)
}

// 分享队伍分组
function shareTeamGroups(dbId) {
  return get('/share/teamGroups', { db_id: dbId }, false)
}

/**
 * ==================== 安全管理 ====================
 */

// 获取主机检查配置
function getHostCheckConfig() {
  return get('/security/host-check')
}

// 保存主机检查配置
function saveHostCheckConfig(data) {
  return post('/security/host-check/save', data)
}

// 获取IP白名单
function getIPWhitelist() {
  return get('/ip-whitelist')
}

// 保存IP白名单
function saveIPWhitelist(data) {
  return post('/ip-whitelist/save', data)
}

/**
 * ==================== 用户管理（管理员） ====================
 */

// 获取用户列表
function getUsers(page = 1, pageSize = 20) {
  return get('/admin/users', { page, page_size: pageSize }, true, false)
}

// 重置用户密码
function resetPassword(userId, newPassword) {
  return post('/admin/users/resetPassword', {
    user_id: userId,
    new_password: newPassword
  }, true, false)
}

// 更新用户状态
function updateUserStatus(userId, status) {
  return post('/admin/users/status', {
    user_id: userId,
    status
  }, true, false)
}

// 更新用户角色
function updateUserRole(userId, role) {
  return post('/admin/users/role', {
    user_id: userId,
    role
  }, true, false)
}

// 删除用户
function deleteUser(userId) {
  return del(`/admin/users/${userId}`, {}, true, false)
}

// 执行数据清理
function executeCleanup() {
  return post('/admin/cleanup/execute', {}, true, false)
}

/**
 * ==================== 数据包捕获 ====================
 */

// 开始抓包
function startPacketCapture(params) {
  return post('/packet-capture/start', params, false)
}

// 停止抓包
function stopPacketCapture() {
  return post('/packet-capture/stop', {}, false)
}

// 获取抓包统计
function getPacketCaptureStats() {
  return get('/packet-capture/stats', {}, false)
}

// 获取抓包数据
function getPacketCapturePackets(params) {
  return get('/packet-capture/packets', params, false)
}

// 导出CSV
function exportPacketCaptureCSV() {
  return get('/packet-capture/export/csv', {}, false)
}

// 导出JSON
function exportPacketCaptureJSON() {
  return get('/packet-capture/export/json', {}, false)
}

/**
 * ==================== 数据清理通知 ====================
 */

// 获取最后清理时间戳
function getLastCleanupTimestamp() {
  return get('/cleanup/timestamp', {}, false)
}

/**
 * ==================== 聊天消息 (724协议) ====================
 */

// 启用聊天消息抓取
function enableGetChatMessage() {
  return post('/enable/getChatMessage', {}, true, true)
}

// 关闭聊天消息抓取
function disableGetChatMessage() {
  return get('/disable/getChatMessage', {}, true, true)
}

// 获取聊天消息列表
function getChatMessageList(params) {
  return get('/chat/messages', params, true, true)
}

// 获取聊天消息统计
function getChatMessageStats() {
  return get('/chat/stats', {}, true, true)
}

// 删除聊天消息
function deleteChatMessages(beforeTime) {
  const params = {}
  if (beforeTime) params.before_time = beforeTime
  return del('/chat/messages', params, true, true)
}

module.exports = {
  // 通用请求方法
  request,
  
  // 认证
  login,
  register,
  logout,
  getUserInfo,
  changePassword,
  selectDatabase,
  
  // 数据库
  getDatabases,
  getDatabaseInfo,
  createDatabase,
  autoGenerateDatabase,
  claimDatabase,
  releaseDatabase,
  updateDatabase,
  deleteDatabase,
  
  // 同盟
  getTeamUsers,
  getTeamGroups,
  
  // 任务
  getTaskList,
  getTaskDetail,
  createTask,
  deleteTask,
  setTaskUserLeave,
  
  // 战报
  enableGetReport,
  disableGetReport,
  getReportNum,
  getTaskReportList,
  statisticsReport,
  deleteTaskReport,
  getGroupWu,
  enableGetBattleReport,
  disableGetBattleReport,
  getReportList,
  getBattleReportDetail,
  getBattleReportList,
  
  // 历史
  getMemberHistory,
  getLandRecords,
  exportLandRecords,
  getLandRecordsStats,
  
  // 玩家队伍
  getPlayerTeam,
  getPlayerTeamByKey,
  
  // 排行榜
  getUnionLeaderboard,
  getPersonalLeaderboard,
  getTerritoryLeaderboard,
  enableGetLeaderboard,
  disableGetLeaderboard,
  
  // 每日报告
  getDailyReportList,
  getDailyReport,
  getDailyReportText,
  generateDailyReport,
  deleteDailyReport,
  
  // 分享
  shareTaskList,
  shareTaskDetail,
  shareTaskReportList,
  shareReportNum,
  shareTeamGroups,
  
  // 安全管理
  getHostCheckConfig,
  saveHostCheckConfig,
  getIPWhitelist,
  saveIPWhitelist,
  
  // 用户管理
  getUsers,
  resetPassword,
  updateUserStatus,
  updateUserRole,
  deleteUser,
  executeCleanup,
  
  // 数据包捕获
  startPacketCapture,
  stopPacketCapture,
  getPacketCaptureStats,
  getPacketCapturePackets,
  exportPacketCaptureCSV,
  exportPacketCaptureJSON,
  
  // 数据清理通知
  getLastCleanupTimestamp,
  
  // 聊天消息
  enableGetChatMessage,
  disableGetChatMessage,
  getChatMessageList,
  getChatMessageStats,
  deleteChatMessages
}
