package api

import (
	"log"
	"strconv"

	"github.com/gin-gonic/gin"
	"stzbHelper/database"
	"stzbHelper/http/common"
	"stzbHelper/middleware"
	"stzbHelper/model"
)

func ListDatabases(c *gin.Context) {
	page := c.DefaultQuery("page", "1")
	pageSize := c.DefaultQuery("page_size", "20")

	pageInt, _ := strconv.Atoi(page)
	pageSizeInt, _ := strconv.Atoi(pageSize)

	userID, _ := c.Get("user_id")
	var uid uint
	if userID != nil {
		uid = userID.(uint)
	}
	isAdmin := middleware.IsAdmin(c)

	log.Printf("[ListDatabases] 用户ID: %d, 是否管理员: %v, 分页: %d/%d", uid, isAdmin, pageInt, pageSizeInt)

	databases, total, err := database.ListGameDatabases(pageInt, pageSizeInt, uid, isAdmin)
	if err != nil {
		log.Printf("[ListDatabases] 查询失败: %v", err)
		common.Response{Code: 500, Message: "获取列表失败"}.Error(c)
		return
	}

	log.Printf("[ListDatabases] 查询成功, 返回 %d 条记录, 总数: %d", len(databases), total)

	common.Response{
		Code:    200,
		Message: "ok",
		Data: gin.H{
			"list":  databases,
			"total": total,
		},
	}.Success(c)
}

func GetDatabaseInfo(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		common.Response{Code: 400, Message: "无效的ID"}.Error(c)
		return
	}

	info, err := database.GetGameDatabaseByID(uint(id))
	if err != nil {
		common.Response{Code: 500, Message: "获取详情失败"}.Error(c)
		return
	}

	stats := gin.H{
		"team_user_count":     0,
		"task_count":          0,
		"report_count":        0,
		"battle_report_count": 0,
	}

	dbName := info["name"].(string)
	gameDB, err := database.GetGameDB(dbName)
	if err == nil && gameDB != nil {
		var teamUserCount int64
		gameDB.Model(&model.TeamUser{}).Count(&teamUserCount)
		stats["team_user_count"] = teamUserCount

		var taskCount int64
		gameDB.Model(&model.Task{}).Count(&taskCount)
		stats["task_count"] = taskCount

		var reportCount int64
		gameDB.Model(&model.Report{}).Count(&reportCount)
		stats["report_count"] = reportCount

		var battleReportCount int64
		gameDB.Model(&model.BattleReport{}).Count(&battleReportCount)
		stats["battle_report_count"] = battleReportCount
	}

	common.Response{
		Code:    200,
		Message: "ok",
		Data: gin.H{
			"database": info,
			"stats":    stats,
		},
	}.Success(c)
}

func CreateDatabase(c *gin.Context) {
	name := c.PostForm("name")
	displayName := c.PostForm("display_name")
	server := c.PostForm("server")
	state := c.PostForm("state")
	allianceName := c.PostForm("alliance_name")

	if name == "" {
		common.Response{Code: 400, Message: "数据库名称不能为空"}.Error(c)
		return
	}

	db, err := database.CreateGameDatabase(name, displayName, server, state, allianceName)
	if err != nil {
		common.Response{Code: 500, Message: "创建失败: " + err.Error()}.Error(c)
		return
	}

	common.Response{
		Code:    200,
		Message: "创建成功",
		Data:    db,
	}.Success(c)
}

func AutoGenerateDatabase(c *gin.Context) {
	common.Response{Code: 501, Message: "功能开发中"}.Error(c)
}

func ClaimDatabase(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		common.Response{Code: 400, Message: "无效的ID"}.Error(c)
		return
	}

	userID, _ := c.Get("user_id")
	var uid uint
	if userID != nil {
		uid = userID.(uint)
	}
	isAdmin := middleware.IsAdmin(c)
	err = database.ClaimDatabase(uint(id), uid, isAdmin)
	if err != nil {
		common.Response{Code: 500, Message: "认领失败: " + err.Error()}.Error(c)
		return
	}

	common.Response{Message: "认领成功"}.Success(c)
}

func ReleaseDatabase(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		common.Response{Code: 400, Message: "无效的ID"}.Error(c)
		return
	}

	userID, _ := c.Get("user_id")
	var uid uint
	if userID != nil {
		uid = userID.(uint)
	}
	isAdmin := middleware.IsAdmin(c)

	err = database.ReleaseDatabase(uint(id), uid, isAdmin)
	if err != nil {
		common.Response{Code: 500, Message: "释放失败: " + err.Error()}.Error(c)
		return
	}

	common.Response{Message: "释放成功"}.Success(c)
}

func UpdateDatabase(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		common.Response{Code: 400, Message: "无效的ID"}.Error(c)
		return
	}

	displayName := c.PostForm("display_name")
	server := c.PostForm("server")
	state := c.PostForm("state")
	allianceName := c.PostForm("alliance_name")
	bindIP := c.PostForm("bind_ip")
	priorityStr := c.PostForm("priority")

	priority := 0
	if priorityStr != "" {
		priority, _ = strconv.Atoi(priorityStr)
	}

	userID, _ := c.Get("user_id")
	var uid uint
	if userID != nil {
		uid = userID.(uint)
	}
	isAdmin := middleware.IsAdmin(c)

	err = database.UpdateGameDatabase(uint(id), displayName, server, state, allianceName, bindIP, priority, uid, isAdmin)
	if err != nil {
		common.Response{Code: 500, Message: "更新失败: " + err.Error()}.Error(c)
		return
	}

	common.Response{Message: "更新成功"}.Success(c)
}

func DeleteDatabase(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		common.Response{Code: 400, Message: "无效的ID"}.Error(c)
		return
	}

	userID, _ := c.Get("user_id")
	var uid uint
	if userID != nil {
		uid = userID.(uint)
	}
	isAdmin := middleware.IsAdmin(c)

	err = database.DeleteGameDatabase(uint(id), uid, isAdmin)
	if err != nil {
		common.Response{Code: 500, Message: "删除失败: " + err.Error()}.Error(c)
		return
	}

	common.Response{Message: "删除成功"}.Success(c)
}
