package api

import (
	"github.com/gin-gonic/gin"
	"stzbHelper/config"
	"stzbHelper/http/handle/api"
	"stzbHelper/middleware"
)

func Register(r *gin.RouterGroup) {
	// 如果启用了主机名检查，应用中间件
	if config.AppConfig.Security.EnableHostCheck {
		r.Use(middleware.HostCheck())
	}

	// ============ 公开接口（无需认证）============
	// 用户认证
	r.POST("auth/register", api.Register)
	r.POST("auth/login", api.Login)
	r.POST("auth/logout", api.Logout)

	// 数据包捕获（公开，但建议在生产环境中添加认证）
	r.POST("packet-capture/start", api.StartPacketCapture)
	r.POST("packet-capture/stop", api.StopPacketCapture)
	r.GET("packet-capture/stats", api.GetCaptureStats)
	r.GET("packet-capture/packets", api.GetCapturedPackets)
	r.GET("packet-capture/export/csv", api.ExportPacketsCSV)
	r.GET("packet-capture/export/json", api.ExportPacketsJSON)

	// ============ 分享访问接口（无需登录，通过db_id参数访问）============
	shareGroup := r.Group("")
	shareGroup.Use(middleware.ShareDBRequired())
	{
		// 任务分享
		shareGroup.GET("share/taskList", api.GetTaskList)
		shareGroup.GET("share/task/:tid", api.GetTask)
		shareGroup.GET("share/taskReportList/:tid", api.GetTaskReportList)
		shareGroup.GET("share/reportNum/:tid", api.GetReportNumByTaskId)
		shareGroup.GET("share/teamGroups", api.GetTeamGroup)
	}

	// ============ 需要认证的接口 ============
	authGroup := r.Group("")
	authGroup.Use(middleware.AuthRequired())
	{
		// 用户信息
		authGroup.GET("user/info", api.GetUserInfo)
		authGroup.POST("user/changePassword", api.ChangePassword)
		authGroup.POST("user/selectDatabase", api.SelectDatabase)

		// 战场实时监控
		authGroup.GET("battlefield-realtime/stats", api.GetBattlefieldRealtimeStats)
		authGroup.GET("battlefield-realtime/packets", api.GetBattlefieldRealtimePackets)
		authGroup.DELETE("battlefield-realtime/packets", api.ClearBattlefieldRealtimePackets)
		authGroup.GET("enable/getBattlefieldRealtime", api.EnableBattlefieldRealtimeCapture)
		authGroup.GET("disable/getBattlefieldRealtime", api.DisableBattlefieldRealtimeCapture)

		// 安全配置管理
		authGroup.GET("security/host-check", api.GetHostCheckConfig)
		authGroup.POST("security/host-check/save", api.SaveHostCheckConfig)

		// IP 白名单管理
		authGroup.GET("ip-whitelist", api.GetIPWhitelist)
		authGroup.POST("ip-whitelist/save", api.SaveIPWhitelist)

		// 数据库管理（不需要选择数据库）
		authGroup.GET("databases", api.ListDatabases)
		authGroup.GET("databases/:id", api.GetDatabaseInfo)
		authGroup.POST("databases/create", api.CreateDatabase)
		authGroup.POST("databases/autoGenerate", api.AutoGenerateDatabase)
		authGroup.POST("databases/:id/claim", api.ClaimDatabase)
		authGroup.POST("databases/:id/release", api.ReleaseDatabase)
		authGroup.PUT("databases/:id", api.UpdateDatabase)
		authGroup.DELETE("databases/:id", api.DeleteDatabase)
	}

	// ============ 需要数据库连接的接口 ============
	dbGroup := r.Group("")
	dbGroup.Use(middleware.AuthRequired(), middleware.DBRequired())
	{
		// 同盟成员
		dbGroup.Any("getTeamUser", api.GetTeamUser)
		dbGroup.Any("getTeamGroup", api.GetTeamGroup)

		// 任务管理
		dbGroup.Any("getTaskList", api.GetTaskList)
		dbGroup.Any("getTask/:tid", api.GetTask)
		dbGroup.POST("createTask", api.CreateTask)
		dbGroup.POST("task/:tid/leave", api.SetTaskUserLeave)
		dbGroup.Any("deleteTask/:tid", api.DelTask)

		// 战报管理
		dbGroup.POST("enable/getReport", api.EnableGetReport)
		dbGroup.Any("disable/getReport", api.DisableGetReport)
		dbGroup.Any("getReportNumByTaskId/:tid", api.GetReportNumByTaskId)
		dbGroup.Any("getTaskReportList/:tid", api.GetTaskReportList)
		dbGroup.Any("statisticsReport/:tid", api.StatisticsReport)
		dbGroup.Any("getGroupWu", api.GetGroupWu)
		dbGroup.Any("deleteTaskReport/:tid", api.DelTaskReport)
		dbGroup.GET("stzb/report/list", api.ReportList)
		dbGroup.Any("enable/getBattleReport", api.EnableGetBattleData)
		dbGroup.Any("disable/getBattleReport", api.DisableGetBattleData)

		// 排行榜抓包开关
		dbGroup.Any("enable/getLeaderboard", api.EnableGetLeaderboard)
		dbGroup.Any("disable/getLeaderboard", api.DisableGetLeaderboard)

		// 聊天消息抓包开关
		dbGroup.Any("enable/getChatMessage", api.EnableGetChatMessage)
		dbGroup.Any("disable/getChatMessage", api.DisableGetChatMessage)

		// 聊天消息
		dbGroup.GET("chat/messages", api.GetChatMessageList)
		dbGroup.GET("chat/stats", api.GetChatMessageStats)
		dbGroup.DELETE("chat/messages", api.DeleteChatMessages)

		// 檄文抓包开关
		dbGroup.Any("enable/getManifesto", api.EnableGetManifesto)
		dbGroup.Any("disable/getManifesto", api.DisableGetManifesto)

		// 战场实时监控（不需要数据库的操作已在 authGroup 中注册）
		dbGroup.GET("ws/realtime-monitor", api.HandleWebSocket)
		dbGroup.GET("battlefield-realtime/teams/search", api.SearchRealtimeTeams)
		dbGroup.GET("statistics/player-teams/realtime-search", api.SearchRealtimeMonitorTeams)

		// 檄文
		dbGroup.GET("manifesto/list", api.GetManifestoList)
		dbGroup.GET("manifesto/stats", api.GetManifestoStats)
		dbGroup.DELETE("manifesto/list", api.DeleteManifestos)

		// 成员历史
		dbGroup.GET("member/history", api.GetMemberHistory)
		dbGroup.GET("land/records", api.GetLandRecords)
		dbGroup.GET("land/records/export", api.ExportLandRecordsExcel)
		dbGroup.GET("land/records/stats", api.GetLandRecordsStats)

		// 战报详情（需要登录）
		dbGroup.GET("battle/report/:battle_id", api.GetBattleReportDetail)
		dbGroup.GET("battle/reports", api.GetBattleReportList)
		dbGroup.DELETE("battle/reports", api.DeleteBattleReports)
		dbGroup.GET("battle/battlefield-stats", api.GetBattlefieldStats)
		dbGroup.POST("battle/migrate-wid", api.MigrateWidFormat)

		// 队伍查询
		dbGroup.GET("stzb/player/team/get", api.GetPlayerTeam)
		dbGroup.GET("stzb/player/team/getByKey", api.GetPlayerTeamByKey)

		// 排行榜看板
		dbGroup.GET("stzb/leaderboard/union", api.UnionLeaderboardList)
		dbGroup.GET("stzb/leaderboard/personal", api.PersonalLeaderboardList)
		dbGroup.GET("stzb/leaderboard/territory", api.PlayerTerritoryRankList)

		// 每日报告
		dbGroup.GET("daily-report/list", api.GetDailyReportList)
		dbGroup.GET("daily-report/:date", api.GetDailyReport)
		dbGroup.GET("daily-report/:date/text", api.GetDailyReportText)
		dbGroup.POST("daily-report/generate", api.GenerateTodayReport)
		dbGroup.DELETE("daily-report/:date", api.DeleteDailyReport)
	}

	// ============ 管理员接口 ============
	adminGroup := r.Group("")
	adminGroup.Use(middleware.AuthRequired(), middleware.AdminRequired())
	{
		// 用户管理
		adminGroup.GET("admin/users", api.ListUsers)
		adminGroup.POST("admin/users/resetPassword", api.ResetPassword)
		adminGroup.POST("admin/users/status", api.UpdateUserStatus)
		adminGroup.POST("admin/users/role", api.UpdateUserRole)
		adminGroup.DELETE("admin/users/:id", api.DeleteUser)

		// 数据清理管理
		adminGroup.POST("admin/cleanup/execute", api.ExecuteCleanup)
	}

	// ============ 小程序公共接口（获取清理时间戳）============
	r.GET("cleanup/timestamp", api.GetLastCleanupTimestamp)
}
